services:
  php:
    build:
      dockerfile: php.dockerfile
      context: docker
    volumes:
      - ".:/var/www/html"
    links:
      - db
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - "./app.conf:/etc/nginx/conf.d/default.conf"
      - ".:/app"
    links:
      - php

  db:
    image: mysql:8.0
    volumes:
      - "db_storage:/var/lib/mysql"
      - "./docker/db:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: test

volumes:
  db_storage:
